name: generate-docs-screenshots

on: push

jobs:
  take-screenshots:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.json') }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, pdo, pdo_sqlite
          coverage: none
      - name: Set up app
        run: |
          cd docs-assets/app
          composer update --prefer-dist --no-interaction
          php artisan serve &
