name: monorepo-split

on:
    push:
        tags: '*'

jobs:
    split-monorepo:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - id: previous-tag
              uses: "WyriHaximus/github-action-get-previous-tag@master"
            - name: Monorepo Split of admin
              uses: symplify/github-action-monorepo-split@main
              env:
                  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
              with:
                  package_directory: ''
                  repository_organization: 'laravel-filament'
                  repository_name: 'admin'
                  branch: 1.x
                  tag: ${{ steps.previous-tag.outputs.tag }}
                  user_name: "Dan Harrin"
                  user_email: "dan@danharrin.com"
